on:
  push:
    branches: 
      - master
jobs:
  npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install npm dependencies
        run: yarn

      - name: Test and build package
        run: |
          yarn test
          yarn run build:lib
      - name: Publish tag to npm
        if: contains(github.ref, 'tags')
        run: yarn publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - uses: actions/setup-node@v1
        with:
          registry-url: 'https://npm.pkg.github.com'

      - name: Publish tag to GPR
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ github.token }}
